/**
 * GOETHE A1 VOCABULARY LIST - PART 1 (A - D)
 * Source: A1_SD1_Wortliste_02.pdf
 */

// Helper to create words quickly and save space
function createWord(id, de, ru, article, examples, fact, distractors) {
    return { id, de, ru: [ru], article, examples, fact, distractors, progress: 0 };
}

const initialData = [
    // --- A ---
    createWord(1, "ab", "с (предлог времени)", "prep", ["Ab morgen muss ich arbeiten."], "Indicates a starting point in time.", ["до", "после", "в"]),
    createWord(2, "aber", "но", "konj", ["Ich bin oft im Büro, aber nur für wenige Stunden.", "Das ist schön, aber teuer."], "Connects two contrasting ideas.", ["и", "или", "потому что"]),
    createWord(3, "abfahren", "отправляться", "verb", ["Wir fahren um zwölf Uhr ab."], "Separable verb: 'Der Zug fährt ab'.", ["прибывать", "спать", "стоять"]),
    createWord(4, "die Abfahrt", "отправление", "die", ["Vor der Abfahrt rufe ich an."], "Opposite of 'Ankunft'.", ["прибытие", "встреча", "остановка"]),
    createWord(5, "abgeben", "сдавать / отдавать", "verb", ["Ich muss meine Schlüssel abgeben."], "Used for handing in keys, coats, or homework.", ["брать", "покупать", "находить"]),
    createWord(6, "abholen", "забирать / встречать", "verb", ["Wann kann ich den Schrank abholen?", "Wir müssen meinen Bruder abholen."], "You 'fetch' people or things.", ["отправлять", "терять", "продавать"]),
    createWord(7, "der Absender", "отправитель", "der", ["Der Brief ist ohne Absender."], "The person who sends the mail.", ["получатель", "почтальон", "письмо"]),
    createWord(8, "Achtung", "Внимание!", "int", ["Achtung! Das dürfen Sie nicht tun."], "Used on warning signs.", ["Привет", "Пока", "Спасибо"]),
    createWord(9, "die Adresse", "адрес", "die", ["Können Sie mir seine Adresse sagen?"], "Don't forget the PLZ (Zip code).", ["Имя", "Телефон", "Город"]),
    createWord(10, "allein", "один / одинокий", "adv", ["Er kommt allein."], "Similar to 'only' or 'solo'.", ["вместе", "с друзьями", "пара"]),
    createWord(11, "also", "итак / следовательно", "adv", ["Er hat Zeit, also muss er uns helfen."], "A very common filler word in German.", ["но", "или", "никогда"]),
    createWord(12, "alt", "старый", "adj", ["Wie alt sind Sie?", "Mein Auto ist schon sehr alt."], "Opposite: neu (objects) or jung (people).", ["новый", "молодой", "красивый"]),
    createWord(13, "das Alter", "возраст", "das", ["Alter: 26 Jahre."], "Noun form of 'alt'.", ["Имя", "Рост", "Вес"]),
    createWord(14, "an", "на / у (предлог)", "prep", ["Wir treffen uns am Bahnhof.", "Das Licht ist an."], "Can mean location or status (on/off).", ["в", "под", "за"]),
    createWord(15, "anbieten", "предлагать", "verb", ["Was darf ich dir anbieten?"], "Noun: das Angebot.", ["брать", "просить", "искать"]),
    createWord(16, "das Angebot", "предложение / акция", "das", ["Heute sind Sportschuhe im Angebot."], "Look for this sign in supermarkets.", ["цена", "деньги", "спрос"]),
    createWord(17, "anfangen", "начинать", "verb", ["Der Unterricht fängt gleich an."], "Synonym: beginnen.", ["заканчивать", "спать", "уходить"]),
    createWord(18, "der Anfang", "начало", "der", ["Sie wohnt am Anfang der Straße."], "Opposite: das Ende.", ["конец", "середина", "угол"]),
    createWord(19, "anklicken", "кликать (мышкой)", "verb", ["Da musst du dieses Wort anklicken."], "Computer vocabulary.", ["писать", "читать", "удалять"]),
    createWord(20, "ankommen", "прибывать", "verb", ["Wann kommt dieser Zug an?"], "Separable verb (an-kommen).", ["уезжать", "уходить", "лететь"]),
    createWord(21, "die Ankunft", "прибытие", "die", ["Auf dem Plan steht nur die Ankunft."], "Opposite: Abfahrt.", ["отправление", "поездка", "билет"]),
    createWord(22, "ankreuzen", "отмечать крестиком", "verb", ["Sie müssen etwas ankreuzen."], "Used in multiple choice tests.", ["писать", "стирать", "читать"]),
    createWord(23, "anmachen", "включать", "verb", ["Mach bitte das Licht an!"], "Opposite: ausmachen.", ["выключать", "ломать", "чинить"]),
    createWord(24, "sich anmelden", "регистрироваться", "verb", ["Wo kann ich mich anmelden?"], "Reflexive verb.", ["выписываться", "играть", "платить"]),
    createWord(25, "die Anmeldung", "регистрация", "die", ["Eine Anmeldung ist nicht mehr möglich."], "You need this at the Bürgeramt.", ["выход", "вход", "касса"]),
    createWord(26, "die Anrede", "обращение (в письме)", "die", ["Schreiben Sie eine Anrede."], "e.g., 'Sehr geehrte Damen und Herren'.", ["подпись", "текст", "дата"]),
    createWord(27, "anrufen", "звонить", "verb", ["Kann man Sie anrufen?", "Er ruft seine Freundin an."], "Separable: Ich rufe an.", ["писать", "приходить", "слушать"]),
    createWord(28, "der Anruf", "звонок", "der", ["Sie bekommt viele Anrufe."], "Noun from anrufen.", ["письмо", "смс", "встреча"]),
    createWord(29, "der Anrufbeantworter", "автоответчик", "der", ["Sprechen Sie auf den Anrufbeantworter."], "Literally: Call-Answerer.", ["телефон", "радио", "телевизор"]),
    createWord(30, "die Ansage", "объявление (по громкой связи)", "die", ["Hören Sie die Ansagen."], "Common at train stations.", ["музыка", "новость", "фильм"]),
    createWord(31, "der Anschluss", "пересадка / подключение", "der", ["In Mannheim haben Sie Anschluss."], "Crucial for train travel.", ["выход", "билет", "вагон"]),
    createWord(32, "antworten", "отвечать", "verb", ["Er antwortet nicht."], "Takes the Dative case (Dat).", ["спрашивать", "молчать", "говорить"]),
    createWord(33, "die Antwort", "ответ", "die", ["Er gibt keine Antwort."], "Opposite: die Frage.", ["вопрос", "проблема", "задача"]),
    createWord(34, "die Anzeige", "объявление (в газете)", "die", ["Ich habe Ihre Anzeige gelesen."], "For jobs or apartments.", ["книга", "статья", "новость"]),
    createWord(35, "sich anziehen", "одеваться", "verb", ["Ich muss mich noch anziehen."], "Opposite: ausziehen.", ["раздеваться", "мыться", "спать"]),
    createWord(36, "das Apartment", "апартаменты / квартира", "das", ["Wir haben ein Apartment gemietet."], "Usually a small flat.", ["дом", "комната", "отель"]),
    createWord(37, "der Apfel", "яблоко", "der", ["Ein Pfund Äpfel bitte."], "Plural: die Äpfel.", ["груша", "банан", "хлеб"]),
    createWord(38, "der Appetit", "аппетит", "der", ["Guten Appetit!"], "Said before eating.", ["жажда", "сон", "голод"]),
    createWord(39, "arbeiten", "работать", "verb", ["Wo arbeiten Sie?"], "Noun: die Arbeit.", ["отдыхать", "гулять", "играть"]),
    createWord(40, "die Arbeit", "работа", "die", ["Mein Bruder sucht Arbeit."], "Can mean job or specific task.", ["отдых", "отпуск", "хобби"]),
    createWord(41, "arbeitslos", "безработный", "adj", ["Er ist schon lange arbeitslos."], "Without work.", ["занятой", "богатый", "счастливый"]),
    createWord(42, "der Arbeitsplatz", "рабочее место", "der", ["An meinem Arbeitsplatz fehlt ein Drucker."], "Where you work.", ["дом", "школа", "парк"]),
    createWord(43, "der Arm", "рука (от плеча)", "der", ["Mein Arm tut weh."], "Distinct from 'Hand'.", ["нога", "голова", "живот"]),
    createWord(44, "der Arzt", "врач", "der", ["Ich muss zum Arzt gehen."], "Female: die Ärztin.", ["учитель", "повар", "водитель"]),
    createWord(45, "auch", "тоже / также", "adv", ["Ich bin auch Spanier."], "Used to agree or add info.", ["нет", "никогда", "только"]),
    createWord(46, "auf", "на (поверхности) / открыто", "prep", ["Das Buch liegt auf dem Tisch.", "Die Tür ist auf."], "Two meanings: on top OR open.", ["под", "в", "за"]),
    createWord(47, "die Aufgabe", "задание / задача", "die", ["Das ist eine schwere Aufgabe."], "Homework = Hausaufgabe.", ["ответ", "игра", "отдых"]),
    createWord(48, "aufhören", "прекращать / заканчивать", "verb", ["Der Kurs hört in einer Woche auf."], "Opposite: anfangen.", ["начинать", "продолжать", "делать"]),
    createWord(49, "aufstehen", "вставать", "verb", ["Ich muss um 4 Uhr aufstehen."], "Getting out of bed.", ["ложиться", "сидеть", "спать"]),
    createWord(50, "der Aufzug", "лифт", "der", ["In diesem Haus gibt es keinen Aufzug."], "Synonym: der Lift.", ["лестница", "дверь", "окно"]),
    createWord(51, "das Auge", "глаз", "das", ["Er hat blaue Augen."], "Plural: die Augen.", ["ухо", "нос", "рот"]),
    createWord(52, "aus", "из / выключено", "prep", ["Er kommt aus Brasilien.", "Das Licht ist aus."], "Origin OR status (off).", ["в", "на", "к"]),
    createWord(53, "der Ausflug", "экскурсия / поездка", "der", ["Wir machen einen Ausflug."], "Short trip.", ["работа", "сон", "урок"]),
    createWord(54, "ausfüllen", "заполнять", "verb", ["Füllen Sie dieses Formular aus."], "Essential for bureaucracy.", ["читать", "рвать", "выбрасывать"]),
    createWord(55, "der Ausgang", "выход", "der", ["Wo ist der Ausgang?"], "Opposite: Eingang.", ["вход", "туалет", "кухня"]),
    createWord(56, "die Auskunft", "справка / информация", "die", ["Können Sie mir eine Auskunft geben?"], "Information desk.", ["вопрос", "проблема", "билет"]),
    createWord(57, "das Ausland", "заграница", "das", ["Fahren Sie ins Ausland?"], "Foreign countries.", ["родина", "город", "дом"]),
    createWord(58, "der Ausländer", "иностранец", "der", ["Sind Sie Ausländer?"], "Female: Ausländerin.", ["друг", "сосед", "родственник"]),
    createWord(59, "ausmachen", "выключать", "verb", ["Mach bitte das Licht aus!"], "Opposite: anmachen.", ["включать", "открывать", "делать"]),
    createWord(60, "die Aussage", "высказывание", "die", ["Ist die Aussage richtig?"], "Used in exam questions.", ["вопрос", "слово", "буква"]),
    createWord(61, "aussehen", "выглядеть", "verb", ["Das sieht schön aus."], "Looks like.", ["слышать", "видеть", "чувствовать"]),
    createWord(62, "aussteigen", "выходить (из транспорта)", "verb", ["Wo muss ich aussteigen?"], "Opposite: einsteigen.", ["садиться", "ехать", "ждать"]),
    createWord(63, "der Ausweis", "паспорт / удостоверение", "der", ["Hier ist mein Ausweis."], "Always carry ID.", ["билет", "деньги", "карта"]),
    createWord(64, "sich ausziehen", "раздеваться", "verb", ["Zieh die Schuhe aus."], "Opposite: anziehen.", ["одеваться", "мыться", "бриться"]),
    createWord(65, "das Auto", "автомобиль", "das", ["Er kommt mit dem Auto."], "Plural: Autos.", ["автобус", "поезд", "велосипед"]),
    createWord(66, "die Autobahn", "автобан / шоссе", "die", ["Wo geht's zur Autobahn?"], "German highways.", ["улица", "дорога", "тропинка"]),
    createWord(67, "der Automat", "автомат", "der", ["Fahrkarten gibt es am Automaten."], "Ticket machine.", ["касса", "человек", "магазин"]),

    // --- B ---
    createWord(68, "das Baby", "младенец", "das", ["Mein Kind ist noch ein Baby."], "Plural: Babys.", ["взрослый", "старик", "подросток"]),
    createWord(69, "die Bäckerei", "пекарня / булочная", "die", ["Ich geh zur Bäckerei."], "Where you buy bread.", ["мясная лавка", "аптека", "школа"]),
    createWord(70, "das Bad", "ванная", "das", ["Wir haben kein großes Bad."], "Short for Badezimmer.", ["кухня", "спальня", "зал"]),
    createWord(71, "baden", "купаться", "verb", ["Ich bade nicht so gern."], "In a tub or lake.", ["душа", "мыть", "плавать"]),
    createWord(72, "die Bahn", "поезд / железная дорога", "die", ["Wir fahren mit der Bahn."], "Deutsche Bahn (DB).", ["автобус", "машина", "такси"]),
    createWord(73, "der Bahnhof", "вокзал", "der", ["Ich bin am Bahnhof."], "Central station: Hauptbahnhof.", ["аэропорт", "порт", "остановка"]),
    createWord(74, "der Bahnsteig", "перрон / платформа", "der", ["Auf welchem Bahnsteig fährt der Zug?"], "Platform number.", ["вагон", "путь", "касса"]),
    createWord(75, "bald", "скоро", "adv", ["Ich komme bald."], "Bis bald! (See you soon).", ["поздно", "никогда", "вчера"]),
    createWord(76, "der Balkon", "балкон", "der", ["Die Wohnung hat einen Balkon."], "Stress on the last syllable.", ["окно", "дверь", "крыша"]),
    createWord(77, "die Banane", "банан", "die", ["Drei Bananen, bitte!"], "Fruit.", ["яблоко", "груша", "картофель"]),
    createWord(78, "die Bank", "банк / скамейка", "die", ["Die Bank schließt um 4.", "Er sitzt auf einer Bank."], "Homonym: Money or Bench.", ["магазин", "стул", "стол"]),
    createWord(79, "bar", "наличными", "adj", ["Muss ich bar zahlen?"], "Cash only.", ["картой", "чеком", "позже"]),
    createWord(80, "der Bauch", "живот", "der", ["Der Bauch tut weh."], "Bauchschmerzen = stomach ache.", ["голова", "нога", "рука"]),
    createWord(81, "der Baum", "дерево", "der", ["Vorsicht, der Baum!"], "Plural: Bäume.", ["цветок", "куст", "трава"]),
    createWord(82, "der Beamte", "чиновник / служащий", "der", ["Fragen Sie den Beamten."], "Works for the state.", ["рабочий", "врач", "учитель"]),
    createWord(83, "bedeuten", "значить", "verb", ["Was bedeutet das Wort?"], "Meaning.", ["говорить", "писать", "читать"]),
    createWord(84, "beginnen", "начинать", "verb", ["Das Spiel beginnt um 15 Uhr."], "Synonym: anfangen.", ["заканчивать", "останавливать", "ждать"]),
    createWord(85, "bei", "у / при / возле", "prep", ["Ich wohne bei meinen Eltern."], "Dative preposition.", ["в", "на", "под"]),
    createWord(86, "beide", "оба", "pron", ["Wir kommen beide."], "Two people/things.", ["один", "никто", "все"]),
    createWord(87, "das Bein", "нога", "das", ["Mein Bein tut weh."], "Distinct from Fuß (foot).", ["рука", "голова", "спина"]),
    createWord(88, "das Beispiel", "пример", "das", ["Zum Beispiel (z.B.)."], "For example.", ["правило", "исключение", "слово"]),
    createWord(89, "bekannt", "известный / знакомый", "adj", ["Picasso ist sehr bekannt."], "Famous.", ["неизвестный", "новый", "чужой"]),
    createWord(90, "der Bekannte", "знакомый", "der", ["Ein Bekannter von mir."], "Someone you know.", ["друг", "враг", "незнакомец"]),
    createWord(91, "bekommen", "получать", "verb", ["Haben Sie meinen Brief bekommen?"], "False friend: NOT 'to become'.", ["отправлять", "терять", "искать"]),
    createWord(92, "benutzen", "использовать", "verb", ["Bitte die Aufzüge nicht benutzen."], "Use.", ["ломать", "смотреть", "покупать"]),
    createWord(93, "der Beruf", "профессия", "der", ["Was sind Sie von Beruf?"], "Job/Career.", ["хобби", "работа", "учеба"]),
    createWord(94, "besetzt", "занято", "adj", ["Der Platz ist besetzt.", "Die Nummer ist besetzt."], "Occupied.", ["свободно", "открыто", "пусто"]),
    createWord(95, "besichtigen", "осматривать (достопримечательности)", "verb", ["Ich möchte den Dom besichtigen."], "Sightseeing.", ["покупать", "строить", "жить"]),
    createWord(96, "besser", "лучше", "adj", ["Es geht mir besser."], "Comparative of 'gut'.", ["хуже", "также", "плохо"]),
    createWord(97, "bestellen", "заказывать", "verb", ["Wir möchten bestellen."], "In a restaurant or online.", ["платить", "готовить", "есть"]),
    createWord(98, "besuchen", "посещать / навещать", "verb", ["Darf ich dich besuchen?"], "Visit.", ["звонить", "писать", "ждать"]),
    createWord(99, "das Bett", "кровать", "das", ["Wir brauchen ein Kinderbett."], "Sleep furniture.", ["диван", "стул", "стол"]),
    createWord(100, "bezahlen", "оплачивать", "verb", ["Wo muss ich bezahlen?"], "Synonym: zahlen.", ["покупать", "брать", "давать"]),
    createWord(101, "das Bier", "пиво", "das", ["Noch ein Bier bitte."], "German staple.", ["вода", "вино", "сок"]),
    createWord(102, "das Bild", "картина / фото", "das", ["Hast du ein Bild von deiner Familie?"], "Picture.", ["книга", "письмо", "окно"]),
    createWord(103, "billig", "дешевый", "adj", ["Die Jacke ist billig."], "Opposite: teuer.", ["дорогой", "бесценный", "красивый"]),
    createWord(104, "die Birne", "груша", "die", ["Ein Kilo Birnen."], "Fruit.", ["яблоко", "банан", "апельсин"]),
    createWord(105, "bis", "до", "prep", ["Ich warte bis morgen."], "Until.", ["от", "с", "после"]),
    createWord(106, "ein bisschen", "немного", "adv", ["Ich spreche ein bisschen Deutsch."], "A little bit.", ["много", "все", "ничего"]),
    createWord(107, "bitte", "пожалуйста", "part", ["Eine Tasse Kaffee, bitte!"], "Please / You're welcome.", ["спасибо", "нет", "да"]),
    createWord(108, "die Bitte", "просьба", "die", ["Ich habe eine Bitte."], "Request.", ["приказ", "вопрос", "ответ"]),
    createWord(109, "bitten", "просить", "verb", ["Darf ich Sie um etwas bitten?"], "To ask for something.", ["давать", "брать", "отвечать"]),
    createWord(110, "bitter", "горький", "adj", ["Der Kaffee schmeckt bitter."], "Taste.", ["сладкий", "соленый", "кислый"]),
    createWord(111, "bleiben", "оставаться", "verb", ["Ich bleibe zu Hause."], "To stay.", ["уходить", "идти", "ехать"]),
    createWord(112, "der Bleistift", "карандаш", "der", ["Hast du einen Bleistift?"], "Writing tool.", ["ручка", "бумага", "книга"]),
    createWord(113, "der Blick", "вид / взгляд", "der", ["Ein Blick auf den Rhein."], "View.", ["слух", "вкус", "запах"]),
    createWord(114, "die Blume", "цветок", "die", ["Gefallen dir die Blumen?"], "Flower.", ["дерево", "трава", "лес"]),
    createWord(115, "böse", "злой / сердитый", "adj", ["Sie ist böse auf mich."], "Angry.", ["добрый", "веселый", "счастливый"]),
    createWord(116, "brauchen", "нуждаться", "verb", ["Brauchst du die Zeitung?"], "Need.", ["иметь", "хотеть", "любить"]),
    createWord(117, "breit", "широкий", "adj", ["Wie breit ist der Schrank?"], "Width.", ["узкий", "высокий", "длинный"]),
    createWord(118, "der Brief", "письмо", "der", ["Haben Sie einen Brief für mich?"], "Letter.", ["газета", "книга", "открытка"]),
    createWord(119, "die Briefmarke", "почтовая марка", "die", ["Kauf bitte Briefmarken."], "Stamp.", ["конверт", "ручка", "клей"]),
    createWord(120, "bringen", "приносить", "verb", ["Bringen Sie mir noch einen Kaffee."], "Bring.", ["брать", "уносить", "давать"]),
    createWord(121, "das Brot", "хлеб", "das", ["Haben Sie Weißbrot?"], "Bread.", ["булочка", "торт", "мясо"]),
    createWord(122, "das Brötchen", "булочка", "das", ["Möchtest du Brötchen?"], "Bread roll.", ["хлеб", "пирог", "сухарь"]),
    createWord(123, "der Bruder", "брат", "der", ["Sein Bruder arbeitet hier."], "Sibling.", ["сестра", "отец", "мать"]),
    createWord(124, "das Buch", "книга", "das", ["Gute Bücher sind teuer."], "Book.", ["тетрадь", "газета", "журнал"]),
    createWord(125, "der Buchstabe", "буква", "der", ["Diesen Buchstaben gibt es nicht."], "Letter (A, B, C).", ["слово", "цифра", "предложение"]),
    createWord(126, "buchstabieren", "диктовать по буквам", "verb", ["Bitte buchstabieren Sie Ihren Namen."], "Spell out.", ["писать", "читать", "говорить"]),
    createWord(127, "der Bus", "автобус", "der", ["Wann kommt der Bus?"], "Public transport.", ["поезд", "машина", "трамвай"]),
    createWord(128, "die Butter", "сливочное масло", "die", ["Brötchen mit Butter."], "Food.", ["хлеб", "сыр", "колбаса"]),

    // --- C ---
    createWord(129, "das Café", "кафе", "das", ["Treffen wir uns im Café?"], "Place for coffee.", ["ресторан", "бар", "дом"]),
    createWord(130, "der Chef", "шеф / начальник", "der", ["Wir haben einen neuen Chef."], "Boss.", ["коллега", "друг", "клиент"]),
    createWord(131, "der Computer", "компьютер", "der", ["Wann bekommst du den Computer?"], "PC.", ["телевизор", "телефон", "радио"]),
    createWord(132, "circa", "примерно", "adv", ["Es sind circa 50 km."], "Approximately (ca.).", ["точно", "ровно", "мало"]),

    // --- D ---
    createWord(133, "da", "тут / там", "adv", ["Ist Herr Klein da?"], "Here/There.", ["нет", "нигде", "везде"]),
    createWord(134, "die Dame", "дама", "die", ["Sehr geehrte Damen und Herren."], "Lady.", ["господин", "девушка", "женщина"]),
    createWord(135, "daneben", "рядом", "adv", ["Daneben ist die Bank."], "Next to it.", ["далеко", "внутри", "сверху"]),
    createWord(136, "danken", "благодарить", "verb", ["Ich danke Ihnen."], "Thank.", ["просить", "ругать", "звать"]),
    createWord(137, "danke", "спасибо", "part", ["Vielen Dank!"], "Thanks.", ["пожалуйста", "нет", "извините"]),
    createWord(138, "dann", "потом / тогда", "adv", ["Dann komme ich."], "Then.", ["сейчас", "раньше", "всегда"]),
    createWord(139, "das Datum", "дата", "das", ["Schreiben Sie das Datum."], "Date.", ["время", "год", "день"]),
    createWord(140, "dauern", "длиться", "verb", ["Wie lange dauert der Film?"], "Lasts.", ["начинаться", "заканчиваться", "идти"]),
    createWord(141, "denn", "так как / же", "konj", ["Ich kann nicht, denn ich bin krank."], "Because (creates causal link).", ["и", "но", "или"]),
    createWord(142, "dieser", "этот", "pron", ["Ich nehme diesen Kuchen."], "This one.", ["тот", "другой", "какой"]),
    createWord(143, "die Disco", "дискотека", "die", ["Wir gehen in die Disco."], "Club.", ["кино", "театр", "парк"]),
    createWord(144, "das Doppelzimmer", "двухместный номер", "das", ["Ein Doppelzimmer bitte."], "Hotel room for two.", ["одноместный номер", "квартира", "дом"]),
    createWord(145, "das Dorf", "деревня", "das", ["Meine Familie lebt in einem Dorf."], "Village.", ["город", "страна", "лес"]),
    createWord(146, "dort", "там", "adv", ["Dort ist unser Haus."], "Over there.", ["здесь", "тут", "близко"]),
    createWord(147, "draußen", "снаружи / на улице", "adv", ["Wollen wir draußen sitzen?"], "Outside.", ["внутри", "дома", "здесь"]),
    createWord(148, "drucken", "печатать", "verb", ["Bitte drucke das Formular."], "Print.", ["писать", "читать", "сканировать"]),
    createWord(149, "der Drucker", "принтер", "der", ["Mein Drucker ist kaputt."], "Machine.", ["компьютер", "сканер", "телефон"]),
    createWord(150, "drücken", "нажимать / толкать", "verb", ["Drück hier."], "Press.", ["тянуть", "бить", "держать"]),
    createWord(151, "die Durchsage", "объявление (по радио/связи)", "die", ["Ich habe die Durchsage nicht verstanden."], "Announcement.", ["разговор", "музыка", "песня"]),
    createWord(152, "der Durst", "жажда", "der", ["Ich habe großen Durst."], "Thirst.", ["голод", "аппетит", "сон"]),
    createWord(153, "sich duschen", "принимать душ", "verb", ["Ich dusche lieber."], "Shower.", ["купаться", "мыться", "плавать"]),
    createWord(154, "die Dusche", "душ", "die", ["Die Wohnung hat eine Dusche."], "Shower.", ["ванна", "туалет", "раковина"]),
    createWord(155, "dürfen", "иметь разрешение (мочь)", "verb", ["Sie dürfen hier nicht rauchen."], "Allowed to.", ["должен", "хотеть", "уметь"]),
    // --- PART 2: E - I ---
// Paste these lines inside your initialData array, or concat them.

    // --- E ---
    createWord(156, "die Ecke", "угол", "die", ["An der nächsten Ecke links."], "Corner.", ["центр", "круг", "середина"]),
    createWord(157, "die Ehefrau", "жена", "die", ["Das ist meine Ehefrau."], "Spouse (female).", ["муж", "друг", "сестра"]),
    createWord(158, "der Ehemann", "муж", "der", ["Das ist mein Ehemann."], "Spouse (male).", ["жена", "брат", "сын"]),
    createWord(159, "das Ei", "яйцо", "das", ["Möchtest du ein Ei zum Frühstück?"], "Plural: Eier.", ["хлеб", "масло", "сыр"]),
    createWord(160, "eilig", "спешный / срочный", "adj", ["Hast du es eilig?"], "In a hurry.", ["медленно", "спокойно", "долго"]),
    createWord(161, "einfach", "простой / (билет) в одну сторону", "adj", ["Die Prüfung ist einfach.", "Einmal Frankfurt, einfach."], "Opposite: schwer OR hin und zurück.", ["сложный", "двойной", "трудный"]),
    createWord(162, "der Eingang", "вход", "der", ["Der Eingang ist um die Ecke."], "Opposite: Ausgang.", ["выход", "окно", "стена"]),
    createWord(163, "einkaufen", "делать покупки", "verb", ["Ich muss einkaufen."], "Grocery shopping.", ["продавать", "смотреть", "гулять"]),
    createWord(164, "einladen", "приглашать", "verb", ["Darf ich Sie einladen?"], "Separable: Ich lade ein.", ["выгонять", "просить", "звать"]),
    createWord(165, "die Einladung", "приглашение", "die", ["Danke für die Einladung."], "Invitation.", ["отказ", "билет", "счет"]),
    createWord(166, "einmal", "один раз", "adv", ["Diese Prüfung mache ich nicht noch einmal."], "Once.", ["дважды", "никогда", "часто"]),
    createWord(167, "einsteigen", "садиться (в транспорт)", "verb", ["Schnell, steig ein!"], "Opposite: aussteigen.", ["выходить", "стоять", "бежать"]),
    createWord(168, "der Eintritt", "вход (плата)", "der", ["Der Eintritt kostet 5 Euro."], "Admission.", ["выход", "цена", "бесплатно"]),
    createWord(169, "das Einzelzimmer", "одноместный номер", "das", ["Haben Sie ein Einzelzimmer?"], "Hotel room for one.", ["двухместный номер", "кровать", "кухня"]),
    createWord(170, "die Eltern", "родители", "pl", ["Meine Eltern leben in Spanien."], "Plural only.", ["дети", "друзья", "соседи"]),
    createWord(171, "die E-Mail", "электронная почта", "die", ["Ich habe Ihre E-Mail nicht bekommen."], "Digital letter.", ["письмо", "факс", "телефон"]),
    createWord(172, "der Empfänger", "получатель", "der", ["Wer ist der Empfänger?"], "Person receiving.", ["отправитель", "почтальон", "друг"]),
    createWord(173, "empfehlen", "рекомендовать", "verb", ["Können Sie mir einen Wein empfehlen?"], "Irregular: er empfiehlt.", ["ругать", "продавать", "пить"]),
    createWord(174, "enden", "заканчиваться", "verb", ["Die Straße endet hier."], "To end.", ["начинаться", "длиться", "идти"]),
    createWord(175, "das Ende", "конец", "das", ["Sie wohnt am Ende der Straße."], "The end.", ["начало", "середина", "угол"]),
    createWord(176, "entschuldigen", "извинять", "verb", ["Entschuldigen Sie bitte!"], "To excuse.", ["обвинять", "ругать", "хвалить"]),
    createWord(177, "die Entschuldigung", "извинение", "die", ["Entschuldigung!"], "Apology.", ["просьба", "приказ", "вопрос"]),
    createWord(178, "das Ergebnis", "результат", "das", ["Das Ergebnis des Tests."], "Result.", ["начало", "процесс", "задача"]),
    createWord(179, "erklären", "объяснять", "verb", ["Kannst du mir das erklären?"], "Explain.", ["спрашивать", "понимать", "забывать"]),
    createWord(180, "erlauben", "разрешать", "verb", ["Rauchen ist nicht erlaubt."], "Allow.", ["запрещать", "просить", "делать"]),
    createWord(181, "der Erwachsene", "взрослый", "der", ["Der Film ist nur für Erwachsene."], "Adult.", ["ребенок", "подросток", "старик"]),
    createWord(182, "erzählen", "рассказывать", "verb", ["Wir müssen euch etwas erzählen."], "Tell a story.", ["молчать", "слушать", "читать"]),
    createWord(183, "essen", "есть / кушать", "verb", ["Was gibt es zu essen?"], "Irregular: er isst.", ["пить", "спать", "готовить"]),
    createWord(184, "das Essen", "еда", "das", ["Das Essen ist gut."], "Food.", ["напиток", "стол", "кухня"]),

    // --- F ---
    createWord(185, "fahren", "ехать", "verb", ["Wir fahren nach Berlin."], "Drive/Go.", ["идти", "лететь", "стоять"]),
    createWord(186, "der Fahrer", "водитель", "der", ["Bitte nicht mit dem Fahrer sprechen."], "Driver.", ["пассажир", "контролер", "врач"]),
    createWord(187, "die Fahrkarte", "билет (проездной)", "die", ["Hast du eine Fahrkarte?"], "Ticket.", ["паспорт", "деньги", "карта"]),
    createWord(188, "das Fahrrad", "велосипед", "das", ["Fährst du mit dem Fahrrad?"], "Bike.", ["машина", "автобус", "поезд"]),
    createWord(189, "falsch", "неправильный / ложный", "adj", ["Das ist falsch."], "Wrong.", ["правильно", "хорошо", "точно"]),
    createWord(190, "die Familie", "семья", "die", ["Meine Familie lebt in Spanien."], "Family.", ["работа", "школа", "группа"]),
    createWord(191, "der Familienstand", "семейное положение", "der", ["Bei Familienstand musst du ledig ankreuzen."], "Marital status.", ["имя", "адрес", "возраст"]),
    createWord(192, "die Farbe", "цвет", "die", ["Die Farbe gefällt mir."], "Color.", ["форма", "размер", "вес"]),
    createWord(193, "feiern", "праздновать", "verb", ["Wir feiern heute Geburtstag."], "Celebrate.", ["работать", "плакать", "спать"]),
    createWord(194, "fehlen", "отсутствовать / не хватать", "verb", ["Herr Müller fehlt heute.", "Was fehlt Ihnen?"], "Missing.", ["быть", "присутствовать", "иметь"]),
    createWord(195, "der Fehler", "ошибка", "der", ["Diesen Fehler mache ich immer."], "Mistake.", ["успех", "правило", "ответ"]),
    createWord(196, "fernsehen", "смотреть телевизор", "verb", ["Wollen wir fernsehen?"], "Watch TV.", ["читать", "слушать", "гулять"]),
    createWord(197, "fertig", "готовый", "adj", ["Bist du fertig?"], "Ready/Finished.", ["начал", "занят", "медленно"]),
    createWord(198, "das Feuer", "огонь / зажигалка", "das", ["Haben Sie Feuer?"], "Fire.", ["вода", "воздух", "земля"]),
    createWord(199, "das Fieber", "температура / жар", "das", ["Ich habe Fieber."], "Fever.", ["здоровье", "боль", "кашель"]),
    createWord(200, "der Film", "фильм", "der", ["Ich möchte den Film sehen."], "Movie.", ["книга", "музыка", "картина"]),
    createWord(201, "finden", "находить / считать (мнение)", "verb", ["Wir müssen den Schlüssel finden.", "Das finde ich gut."], "Find.", ["терять", "искать", "забывать"]),
    createWord(202, "die Firma", "фирма", "die", ["Er arbeitet bei einer Firma."], "Company.", ["школа", "магазин", "дом"]),
    createWord(203, "der Fisch", "рыба", "der", ["Ich esse gern Fisch."], "Fish.", ["мясо", "птица", "овощи"]),
    createWord(204, "die Flasche", "бутылка", "die", ["Eine Flasche Bier bitte."], "Bottle.", ["стакан", "чашка", "банка"]),
    createWord(205, "das Fleisch", "мясо", "das", ["Fleisch mag ich nicht."], "Meat.", ["рыба", "хлеб", "овощи"]),
    createWord(206, "fliegen", "летать", "verb", ["Ich fliege nicht gern."], "Fly.", ["ехать", "плыть", "идти"]),
    createWord(207, "abfliegen", "вылетать", "verb", ["Wann fliegst du ab?"], "Depart (plane).", ["прилетать", "садиться", "падать"]),
    createWord(208, "der Abflug", "вылет", "der", ["Der Abflug ist um 11 Uhr."], "Departure.", ["прилет", "посадка", "билет"]),
    createWord(209, "der Flughafen", "аэропорт", "der", ["Zum Flughafen bitte."], "Airport.", ["вокзал", "порт", "станция"]),
    createWord(210, "das Flugzeug", "самолет", "das", ["Das Flugzeug kommt später an."], "Airplane.", ["поезд", "автобус", "машина"]),
    createWord(211, "das Formular", "бланк / форма", "das", ["Füllen Sie das Formular aus."], "Form.", ["письмо", "книга", "газета"]),
    createWord(212, "das Foto", "фотография", "das", ["Darf ich ein Foto machen?"], "Photo.", ["рисунок", "картина", "кино"]),
    createWord(213, "fragen", "спрашивать", "verb", ["Darf ich etwas fragen?"], "Ask.", ["отвечать", "говорить", "знать"]),
    createWord(214, "die Frage", "вопрос", "die", ["Ich habe eine Frage."], "Question.", ["ответ", "решение", "совет"]),
    createWord(215, "die Frau", "женщина / госпожа", "die", ["Das ist Frau Becker."], "Woman/Mrs.", ["мужчина", "ребенок", "господин"]),
    createWord(216, "frei", "свободный", "adj", ["Ist der Platz frei?"], "Free/Empty.", ["занят", "полный", "дорогой"]),
    createWord(217, "die Freizeit", "свободное время", "die", ["In meiner Freizeit spiele ich Fußball."], "Leisure time.", ["работа", "учеба", "сон"]),
    createWord(218, "fremd", "чужой / незнакомый", "adj", ["Ich bin fremd hier."], "Foreign/Stranger.", ["знакомый", "родной", "свой"]),
    createWord(219, "sich freuen", "радоваться", "verb", ["Ich freue mich auf den Urlaub."], "To be happy about.", ["грустить", "плакать", "бояться"]),
    createWord(220, "der Freund", "друг", "der", ["Das ist ein Freund von mir."], "Friend (male).", ["враг", "сосед", "коллега"]),
    createWord(221, "früher", "раньше", "adv", ["Früher waren wir oft im Kino."], "Earlier/In the past.", ["позже", "сейчас", "завтра"]),
    createWord(222, "frühstücken", "завтракать", "verb", ["Ich frühstücke um 8 Uhr."], "Eat breakfast.", ["обедать", "ужинать", "спать"]),
    createWord(223, "das Frühstück", "завтрак", "das", ["Möchtest du ein Ei zum Frühstück?"], "Breakfast.", ["обед", "ужин", "полдник"]),
    createWord(224, "die Führung", "экскурсия (с гидом)", "die", ["Die Führung beginnt gleich."], "Guided tour.", ["прогулка", "поездка", "сон"]),
    createWord(225, "für", "для", "prep", ["Das ist für Sie."], "For.", ["без", "с", "от"]),
    createWord(226, "der Fuß", "стопа / нога", "der", ["Der Fuß tut weh."], "Foot.", ["рука", "голова", "живот"]),
    createWord(227, "der Fußball", "футбол", "der", ["Spielt ihr Fußball?"], "Soccer.", ["теннис", "хоккей", "спорт"]),

    // --- G ---
    createWord(228, "der Garten", "сад", "der", ["Wir haben einen Garten."], "Garden.", ["лес", "парк", "дом"]),
    createWord(229, "der Gast", "гость", "der", ["Wir haben Gäste."], "Guest.", ["хозяин", "друг", "сосед"]),
    createWord(230, "geben", "давать", "verb", ["Kannst du mir das Buch geben?"], "Give.", ["брать", "получать", "искать"]),
    createWord(231, "geboren", "рожденный", "adj", ["Ich bin in Berlin geboren."], "Born.", ["умер", "жил", "был"]),
    createWord(232, "das Geburtsjahr", "год рождения", "das", ["Ihr Geburtsjahr bitte."], "Birth year.", ["имя", "адрес", "дата"]),
    createWord(233, "der Geburtsort", "место рождения", "der", ["Geburtsort: München."], "Birthplace.", ["город", "страна", "дом"]),
    createWord(234, "der Geburtstag", "день рождения", "der", ["Herzlichen Glückwunsch zum Geburtstag!"], "Birthday.", ["праздник", "выходной", "юбилей"]),
    createWord(235, "gefallen", "нравиться", "verb", ["Das gefällt mir."], "To please.", ["ненавидеть", "любить", "хотеть"]),
    createWord(236, "gegen", "против / около (время)", "prep", ["Wer spielt gegen wen?"], "Against.", ["за", "с", "для"]),
    createWord(237, "gehen", "идти", "verb", ["Ich muss jetzt gehen."], "Go/Walk.", ["стоять", "сидеть", "лежать"]),
    createWord(238, "gehören", "принадлежать", "verb", ["Wem gehört das?"], "Belong to.", ["иметь", "быть", "брать"]),
    createWord(239, "das Geld", "деньги", "das", ["Hast du Geld?"], "Money.", ["золото", "карта", "цена"]),
    createWord(240, "das Gemüse", "овощи", "das", ["Wir kaufen Gemüse."], "Vegetables.", ["фрукты", "мясо", "хлеб"]),
    createWord(241, "das Gepäck", "багаж", "das", ["Ist Ihr Gepäck schwer?"], "Luggage.", ["сумка", "рука", "билет"]),
    createWord(242, "gerade", "прямо сейчас / прямой", "adv", ["Da kommt er gerade."], "Just now/Straight.", ["потом", "криво", "давно"]),
    createWord(243, "geradeaus", "прямо", "adv", ["Gehen Sie immer geradeaus."], "Straight ahead.", ["налево", "направо", "назад"]),
    createWord(244, "gern", "охотно / с удовольствием", "adv", ["Ich gehe gern ins Kino."], "Gladly.", ["неохотно", "никогда", "плохо"]),
    createWord(245, "das Geschäft", "магазин", "das", ["Die Geschäfte schließen gleich."], "Shop.", ["школа", "банк", "парк"]),
    createWord(246, "das Geschenk", "подарок", "das", ["Danke für das Geschenk."], "Gift.", ["покупка", "сюрприз", "деньги"]),
    createWord(247, "die Geschwister", "братья и сестры", "pl", ["Ich habe keine Geschwister."], "Siblings.", ["родители", "дети", "друзья"]),
    createWord(248, "das Gespräch", "разговор", "das", ["Das Gespräch war kurz."], "Conversation.", ["молчание", "песня", "текст"]),
    createWord(249, "gestern", "вчера", "adv", ["Gestern war ich krank."], "Yesterday.", ["сегодня", "завтра", "сейчас"]),
    createWord(250, "das Getränk", "напиток", "das", ["Mein Lieblingsgetränk ist Cola."], "Drink.", ["еда", "вода", "сок"]),
    createWord(251, "das Gewicht", "вес", "das", ["Sein Gewicht ist normal."], "Weight.", ["рост", "размер", "возраст"]),
    createWord(252, "gewinnen", "выигрывать", "verb", ["Wer gewinnt das Spiel?"], "Win.", ["проигрывать", "терять", "искать"]),
    createWord(253, "das Glas", "стакан / стекло", "das", ["Ein Glas Wasser bitte."], "Glass.", ["чашка", "кружка", "бутылка"]),
    createWord(254, "glauben", "верить / полагать", "verb", ["Ich glaube, er kommt gleich."], "Believe/Think.", ["знать", "видеть", "слышать"]),
    createWord(255, "gleich", "сейчас / одинаковый", "adv", ["Ich komme gleich.", "Wir sind gleich alt."], "Immediately/Same.", ["потом", "разный", "позже"]),
    createWord(256, "das Gleis", "путь (на вокзале)", "das", ["Der Zug hält an Gleis 8."], "Track.", ["перрон", "вагон", "место"]),
    createWord(257, "das Glück", "счастье / удача", "das", ["Viel Glück!"], "Luck.", ["беда", "горе", "успех"]),
    createWord(258, "glücklich", "счастливый", "adj", ["Sie sind glücklich."], "Happy.", ["грустный", "злой", "больной"]),
    createWord(259, "der Glückwunsch", "поздравление", "der", ["Herzlichen Glückwunsch!"], "Congratulation.", ["привет", "подарок", "желание"]),
    createWord(260, "gratulieren", "поздравлять", "verb", ["Ich gratuliere dir."], "Congratulate.", ["желать", "дарить", "хвалить"]),
    createWord(261, "grillen", "жарить на гриле", "verb", ["Wir grillen im Garten."], "Barbecue.", ["варить", "печь", "есть"]),
    createWord(262, "groß", "большой / высокий (о росте)", "adj", ["Frankfurt ist groß."], "Big/Tall.", ["маленький", "низкий", "узкий"]),
    createWord(263, "die Größe", "размер", "die", ["Welche Größe haben Sie?"], "Size.", ["цвет", "форма", "вес"]),
    createWord(264, "die Großeltern", "бабушка и дедушка", "pl", ["Meine Großeltern wohnen hier."], "Grandparents.", ["родители", "дети", "внуки"]),
    createWord(265, "die Gruppe", "группа", "die", ["Die erste Gruppe beginnt."], "Group.", ["класс", "команда", "пара"]),
    createWord(266, "der Gruß", "приветствие", "der", ["Viele Grüße!"], "Greeting.", ["прощание", "ответ", "вопрос"]),
    createWord(267, "gültig", "действительный", "adj", ["Der Pass ist gültig."], "Valid.", ["старый", "новый", "плохой"]),
    createWord(268, "günstig", "выгодный / недорогой", "adj", ["Das ist günstig."], "Cheap/Favorable.", ["дорогой", "плохой", "старый"]),
    createWord(269, "gut", "хороший", "adj", ["Das finde ich gut."], "Good.", ["плохой", "злой", "старый"]),

    // --- H ---
    createWord(270, "das Haar", "волосы", "das", ["Sie hat lange Haare."], "Hair.", ["голова", "лицо", "глаз"]),
    createWord(271, "haben", "иметь", "verb", ["Ich habe ein Auto."], "Have.", ["быть", "дать", "брать"]),
    createWord(272, "das Hähnchen", "курица (блюдо)", "das", ["Ein Hähnchen mit Pommes."], "Chicken.", ["мясо", "рыба", "суп"]),
    createWord(273, "die Halbpension", "полупансион", "die", ["Hotel mit Halbpension."], "Half-board.", ["завтрак", "ужин", "отель"]),
    createWord(274, "hallo", "привет", "int", ["Hallo, wie geht's?"], "Hello.", ["пока", "прощай", "спасибо"]),
    createWord(275, "halten", "останавливаться", "verb", ["Der Zug hält hier nicht."], "Stop.", ["ехать", "идти", "бежать"]),
    createWord(276, "die Haltestelle", "остановка", "die", ["An der nächsten Haltestelle."], "Stop (Bus/Tram).", ["вокзал", "аэропорт", "метро"]),
    createWord(277, "die Hand", "кисть руки", "die", ["Gib mir die Hand."], "Hand.", ["нога", "голова", "палец"]),
    createWord(278, "das Handy", "мобильный телефон", "das", ["Ist das dein Handy?"], "Mobile phone.", ["телефон", "компьютер", "радио"]),
    createWord(279, "das Haus", "дом", "das", ["Ich gehe nach Hause."], "House.", ["квартира", "комната", "школа"]),
    createWord(280, "die Hausaufgabe", "домашнее задание", "die", ["Mach deine Hausaufgaben!"], "Homework.", ["урок", "тест", "игра"]),
    createWord(281, "die Heimat", "родина", "die", ["Meine Heimat ist Italien."], "Homeland.", ["страна", "город", "дом"]),
    createWord(282, "heiraten", "жениться / выходить замуж", "verb", ["Sie heiratet einen Italiener."], "Marry.", ["разводиться", "встречаться", "дружить"]),
    createWord(283, "heißen", "называться / звать", "verb", ["Ich heiße Peter."], "Be called.", ["быть", "жить", "делать"]),
    createWord(284, "helfen", "помогать", "verb", ["Können Sie mir helfen?"], "Help.", ["мешать", "делать", "просить"]),
    createWord(285, "hell", "светлый", "adj", ["Im Sommer ist es lange hell."], "Bright/Light.", ["темный", "черный", "ночь"]),
    createWord(286, "der Herd", "плита (кухонная)", "der", ["Der Herd ist neu."], "Stove.", ["холодильник", "стол", "шкаф"]),
    createWord(287, "der Herr", "господин", "der", ["Guten Tag, Herr Müller."], "Mr./Gentleman.", ["фрау", "женщина", "друг"]),
    createWord(288, "herzlich", "сердечный", "adj", ["Herzlich willkommen!"], "Cordial.", ["холодный", "злой", "грубый"]),
    createWord(289, "heute", "сегодня", "adv", ["Heute ist Montag."], "Today.", ["завтра", "вчера", "сейчас"]),
    createWord(290, "hier", "здесь", "adv", ["Hier wohne ich."], "Here.", ["там", "далеко", "где-то"]),
    createWord(291, "die Hilfe", "помощь", "die", ["Brauchen Sie Hilfe?"], "Help.", ["совет", "деньги", "вопрос"]),
    createWord(292, "hinten", "сзади", "adv", ["Die Tür ist hinten."], "Behind/Back.", ["впереди", "сверху", "снизу"]),
    createWord(293, "das Hobby", "хобби", "das", ["Mein Hobby ist Fußball."], "Hobby.", ["работу", "учебу", "дело"]),
    createWord(294, "hoch", "высокий", "adj", ["Der Berg ist hoch."], "High.", ["низкий", "глубокий", "широкий"]),
    createWord(295, "die Hochzeit", "свадьба", "die", ["Wir feiern Hochzeit."], "Wedding.", ["похороны", "праздник", "день рождения"]),
    createWord(296, "holen", "приносить / забирать", "verb", ["Ich hole das Wasser."], "Get/Fetch.", ["относить", "давать", "бросать"]),
    createWord(297, "hören", "слышать / слушать", "verb", ["Ich höre Musik."], "Hear/Listen.", ["видеть", "говорить", "читать"]),
    createWord(298, "das Hotel", "отель", "das", ["Wir wohnen im Hotel."], "Hotel.", ["дом", "квартира", "комната"]),
    createWord(299, "der Hund", "собака", "der", ["Hast du einen Hund?"], "Dog.", ["кошка", "мышь", "птица"]),
    createWord(300, "der Hunger", "голод", "der", ["Ich habe Hunger."], "Hunger.", ["жажда", "аппетит", "сон"]),

    // --- I ---
    createWord(301, "ich", "я", "pron", ["Ich heiße Anna."], "I.", ["ты", "он", "мы"]),
    createWord(302, "ihr", "вы (мн.ч. разг.) / её", "pron", ["Kommt ihr mit?", "Das ist ihr Buch."], "You (plural) OR Her.", ["мы", "они", "он"]),
    createWord(303, "immer", "всегда", "adv", ["Er kommt immer zu spät."], "Always.", ["никогда", "иногда", "часто"]),
    createWord(304, "in", "в", "prep", ["Ich wohne in Berlin."], "In.", ["на", "у", "под"]),
    createWord(305, "die Information", "информация / справка", "die", ["Gehen Sie zur Information."], "Info desk.", ["касса", "выход", "вход"]),
    createWord(306, "international", "международный", "adj", ["Der Kurs ist international."], "International.", ["национальный", "местный", "немецкий"]),
    createWord(307, "das Internet", "интернет", "das", ["Das findest du im Internet."], "Internet.", ["газета", "книга", "радио"]),

    // --- PART 3: J - M ---
// Paste inside initialData array

    // --- J ---
    createWord(308, "ja", "да", "part", ["Sind Sie Herr Watanabe? - Ja."], "Yes.", ["нет", "возможно", "никогда"]),
    createWord(309, "die Jacke", "куртка / пиджак", "die", ["Zieh dir eine Jacke an."], "Jacket.", ["пальто", "рубашка", "брюки"]),
    createWord(310, "jeder", "каждый", "pron", ["Jeder muss das wissen."], "Every/Each.", ["никто", "все", "некоторые"]),
    createWord(311, "jetzt", "сейчас", "adv", ["Jetzt machen wir eine Pause."], "Now.", ["потом", "завтра", "вчера"]),
    createWord(312, "der Job", "работа (временная)", "der", ["Ich habe einen neuen Job."], "Job.", ["хобби", "отпуск", "учеба"]),
    createWord(313, "der Jugendliche", "подросток", "der", ["Viele Jugendliche kaufen gern ein."], "Youth/Teenager.", ["ребенок", "взрослый", "старик"]),
    createWord(314, "jung", "молодой", "adj", ["Sie ist noch jung."], "Young.", ["старый", "взрослый", "пожилой"]),
    createWord(315, "der Junge", "мальчик", "der", ["Ich habe zwei Kinder: einen Jungen und ein Mädchen."], "Boy.", ["девочка", "мужчина", "женщина"]),

    // --- K ---
    createWord(316, "der Kaffee", "кофе", "der", ["Zum Frühstück trinke ich Kaffee."], "Coffee.", ["чай", "вода", "сок"]),
    createWord(317, "kaputt", "сломанный", "adj", ["Das Glas ist kaputt."], "Broken.", ["целый", "новый", "хороший"]),
    createWord(318, "die Karte", "карта / открытка / билет", "die", ["Ich schreibe eine Karte.", "Kann ich mit Karte zahlen?"], "Card/Ticket.", ["письмо", "деньги", "бумага"]),
    createWord(319, "die Kartoffel", "картофель", "die", ["Ich esse gern Kartoffeln."], "Potato.", ["рис", "макароны", "хлеб"]),
    createWord(320, "die Kasse", "касса", "die", ["Zahlen Sie bitte an der Kasse."], "Checkout/Register.", ["выход", "вход", "полка"]),
    createWord(321, "kaufen", "покупать", "verb", ["Tim kauft ein neues Auto."], "Buy.", ["продавать", "смотреть", "брать"]),
    createWord(322, "kein", "никакой (отрицание)", "pron", ["Ich habe keine Zeit."], "No/None.", ["много", "все", "есть"]),
    createWord(323, "kennen", "знать (кого-то/что-то)", "verb", ["Kennen Sie diese Frau?"], "Know (people/places).", ["понимать", "учить", "забывать"]),
    createWord(324, "kennenlernen", "знакомиться", "verb", ["Wir möchten Sie kennenlernen."], "Get to know.", ["прощаться", "встречать", "видеть"]),
    createWord(325, "das Kind", "ребенок", "das", ["Wie viele Kinder haben Sie?"], "Child.", ["взрослый", "родитель", "друг"]),
    createWord(326, "der Kindergarten", "детский сад", "der", ["Die Kleine geht in den Kindergarten."], "Kindergarten.", ["школа", "университет", "работа"]),
    createWord(327, "das Kino", "кинотеатр", "das", ["Wir gehen heute ins Kino."], "Cinema.", ["театр", "цирк", "парк"]),
    createWord(328, "der Kiosk", "киоск", "der", ["Zeitungen gibt es am Kiosk."], "Kiosk.", ["магазин", "рынок", "аптека"]),
    createWord(329, "klar", "ясно / конечно", "adj", ["Kommst du mit? - Klar!"], "Clear/Sure.", ["нет", "неясно", "плохо"]),
    createWord(330, "die Klasse", "класс", "die", ["In unserer Klasse sind 25 Schüler."], "Class.", ["школа", "группа", "урок"]),
    createWord(331, "die Kleidung", "одежда", "die", ["Wo finde ich Kleidung?"], "Clothing.", ["обувь", "еда", "мебель"]),
    createWord(332, "klein", "маленький", "adj", ["Eltville ist eine kleine Stadt."], "Small.", ["большой", "высокий", "длинный"]),
    createWord(333, "kochen", "готовить / варить", "verb", ["Er kann gut kochen."], "Cook.", ["есть", "пить", "спать"]),
    createWord(334, "der Koffer", "чемодан", "der", ["Ist das Ihr Koffer?"], "Suitcase.", ["сумка", "пакет", "рюкзак"]),
    createWord(335, "der Kollege", "коллега", "der", ["Wie heißt der neue Kollege?"], "Colleague.", ["друг", "шеф", "сосед"]),
    createWord(336, "kommen", "приходить / приезжать", "verb", ["Woher kommen Sie?"], "Come.", ["уходить", "ехать", "стоять"]),
    createWord(337, "können", "мочь / уметь", "verb", ["Ich kann Deutsch."], "Can/Be able to.", ["должен", "хотеть", "знать"]),
    createWord(338, "das Konto", "счет (банковский)", "das", ["Das Geld kommt auf Ihr Konto."], "Account.", ["карта", "банк", "деньги"]),
    createWord(339, "der Kopf", "голова", "der", ["Mein Kopf tut weh."], "Head.", ["рука", "нога", "живот"]),
    createWord(340, "kosten", "стоить", "verb", ["Wie viel kostet das?"], "Cost.", ["платить", "покупать", "продавать"]),
    createWord(341, "krank", "больной", "adj", ["Ich kann nicht kommen, ich bin krank."], "Sick.", ["здоровый", "сильный", "веселый"]),
    createWord(342, "kriegen", "получать (разг.)", "verb", ["Ich kriege 15 Euro."], "Get (informal).", ["давать", "терять", "искать"]),
    createWord(343, "die Küche", "кухня", "die", ["Der Herd steht in der Küche."], "Kitchen.", ["ванная", "спальня", "зал"]),
    createWord(344, "der Kuchen", "пирог / торт", "der", ["Ich nehme ein Stück Kuchen."], "Cake.", ["хлеб", "печенье", "конфета"]),
    createWord(345, "der Kugelschreiber", "шариковая ручка", "der", ["Hast du einen Kugelschreiber?"], "Pen.", ["карандаш", "фломастер", "кисть"]),
    createWord(346, "der Kühlschrank", "холодильник", "der", ["Die Milch steht im Kühlschrank."], "Fridge.", ["плита", "шкаф", "стол"]),
    createWord(347, "kulturell", "культурный", "adj", ["Ich bin kulturell interessiert."], "Cultural.", ["спортивный", "скучный", "плохой"]),
    createWord(348, "sich kümmern", "заботиться", "verb", ["Die Mutter kümmert sich um das Kind."], "Take care of.", ["забывать", "бросать", "игнорировать"]),
    createWord(349, "der Kunde", "клиент / покупатель", "der", ["Ich habe einen Kunden."], "Customer.", ["продавец", "кассир", "шеф"]),
    createWord(350, "der Kurs", "курс", "der", ["Der Deutschkurs geht bis Sommer."], "Course.", ["урок", "школа", "книга"]),
    createWord(351, "kurz", "короткий", "adj", ["Er hat kurzes Haar."], "Short.", ["длинный", "высокий", "большой"]),

    // --- L ---
    createWord(352, "lachen", "смеяться", "verb", ["Die Kinder lachen viel."], "Laugh.", ["плакать", "кричать", "молчать"]),
    createWord(353, "der Laden", "магазин / лавка", "der", ["Im Buchladen kaufen."], "Shop.", ["рынок", "склад", "дом"]),
    createWord(354, "das Land", "страна / сельская местность", "das", ["Italien ist ein schönes Land."], "Country.", ["город", "деревня", "мир"]),
    createWord(355, "lang", "длинный", "adj", ["Die Jeans ist zu lang."], "Long.", ["короткий", "широкий", "узкий"]),
    createWord(356, "lange", "долго", "adv", ["Wie lange dauert der Film?"], "Long time.", ["быстро", "коротко", "мало"]),
    createWord(357, "langsam", "медленно", "adj", ["Könnten Sie bitte langsamer sprechen?"], "Slow.", ["быстро", "громко", "тихо"]),
    createWord(358, "laufen", "бегать / ходить пешком", "verb", ["Ich möchte laufen."], "Run/Walk.", ["стоять", "сидеть", "лежать"]),
    createWord(359, "laut", "громкий", "adj", ["Nicht so laut!"], "Loud.", ["тихий", "спокойный", "нежный"]),
    createWord(360, "leben", "жить", "verb", ["Sie lebt bei ihrer Schwester."], "Live (be alive/reside).", ["умереть", "спать", "работать"]),
    createWord(361, "das Leben", "жизнь", "das", ["Das Leben ist teuer."], "Life.", ["смерть", "сон", "мечта"]),
    createWord(362, "die Lebensmittel", "продукты питания", "pl", ["Lebensmittel im Supermarkt kaufen."], "Groceries.", ["одежда", "мебель", "техника"]),
    createWord(363, "ledig", "холостой / незамужняя", "adj", ["Sind Sie verheiratet? Nein, ledig."], "Single.", ["женат", "замужем", "вдовец"]),
    createWord(364, "legen", "класть", "verb", ["Legen Sie das Buch auf den Tisch."], "Lay/Put.", ["ставить", "вешать", "бросать"]),
    createWord(365, "der Lehrer", "учитель", "der", ["Unsere Lehrerin heißt Frau Müller."], "Teacher.", ["ученик", "студент", "директор"]),
    createWord(366, "leicht", "легкий", "adj", ["Der Koffer ist leicht.", "Deutsch ist nicht leicht."], "Light/Easy.", ["тяжелый", "сложный", "трудный"]),
    createWord(367, "leider", "к сожалению", "adv", ["Leider kann ich nicht kommen."], "Unfortunately.", ["конечно", "к счастью", "наверное"]),
    createWord(368, "leise", "тихий", "adj", ["Seid leise!"], "Quiet.", ["громкий", "шумный", "звонкий"]),
    createWord(369, "lernen", "учить", "verb", ["Wie lange lernen Sie schon Deutsch?"], "Learn.", ["знать", "уметь", "забывать"]),
    createWord(370, "lesen", "читать", "verb", ["Ich lese ein Buch."], "Read.", ["писать", "говорить", "слышать"]),
    createWord(371, "letzter", "последний", "adj", ["Morgen ist der letzte Tag."], "Last.", ["первый", "второй", "следующий"]),
    createWord(372, "die Leute", "люди", "pl", ["In der Disko sind viele Leute."], "People.", ["человек", "друзья", "семья"]),
    createWord(373, "das Licht", "свет", "das", ["Mach bitte das Licht an."], "Light.", ["темнота", "тень", "ночь"]),
    createWord(374, "lieben", "любить", "verb", ["Ich liebe dich."], "Love.", ["ненавидеть", "нравиться", "дружить"]),
    createWord(375, "lieber", "лучше / охотнее", "adv", ["Ich nehme lieber Tee."], "Preferably.", ["хуже", "меньше", "больше"]),
    createWord(376, "Lieblings-", "любимый (приставка)", "prefix", ["Mein Lieblingsfilm."], "Favorite...", ["плохой", "скучный", "новый"]),
    createWord(377, "das Lied", "песня", "das", ["Welches ist dein Lieblingslied?"], "Song.", ["музыка", "стих", "книга"]),
    createWord(378, "liegen", "лежать / находиться", "verb", ["Frankfurt liegt am Main."], "Lie/Located.", ["стоять", "сидеть", "идти"]),
    createWord(379, "links", "слева / налево", "adv", ["Gehen Sie nach links."], "Left.", ["справа", "прямо", "назад"]),
    createWord(380, "der Lkw", "грузовик", "der", ["Der Lkw ist groß."], "Truck.", ["машина", "автобус", "поезд"]),
    createWord(381, "das Lokal", "кафе / ресторан", "das", ["Es gibt ein neues Lokal."], "Pub/Restaurant.", ["дом", "магазин", "кино"]),
    createWord(382, "die Lösung", "решение", "die", ["Die Lösung ist einfach."], "Solution.", ["проблема", "вопрос", "ошибка"]),
    createWord(383, "lustig", "веселый / смешной", "adj", ["Der Film war lustig."], "Funny.", ["грустный", "скучный", "серьезный"]),

    // --- M ---
    createWord(384, "machen", "делать", "verb", ["Was machst du heute?"], "Do/Make.", ["спать", "лениться", "отдыхать"]),
    createWord(385, "das Mädchen", "девочка / девушка", "das", ["Junge oder Mädchen?"], "Girl.", ["мальчик", "мужчина", "женщина"]),
    createWord(386, "man", "человек (неопред.)", "pron", ["Hier darf man nicht rauchen."], "One/People.", ["я", "ты", "мы"]),
    createWord(387, "der Mann", "мужчина / муж", "der", ["Mein Mann arbeitet bei der Polizei."], "Man/Husband.", ["женщина", "жена", "ребенок"]),
    createWord(388, "männlich", "мужской (пол)", "adj", ["Kreuzen Sie an: männlich."], "Male.", ["женский", "детский", "средний"]),
    createWord(389, "die Maschine", "машина (механизм)", "die", ["Die Waschmaschine."], "Machine.", ["компьютер", "телефон", "инструмент"]),
    createWord(390, "das Meer", "море", "das", ["Wir machen Urlaub am Meer."], "Sea.", ["горы", "лес", "город"]),
    createWord(391, "mehr", "больше", "adv", ["Ich möchte mehr Geld."], "More.", ["меньше", "мало", "много"]),
    createWord(392, "mein", "мой", "pron", ["Das ist mein Vater."], "My.", ["твой", "наш", "ваш"]),
    createWord(393, "meistens", "чаще всего", "adv", ["Die meisten Leute."], "Mostly.", ["никогда", "редко", "иногда"]),
    createWord(394, "der Mensch", "человек", "der", ["Die Menschen sind hier nett."], "Human.", ["животное", "робот", "вещь"]),
    createWord(395, "mieten", "снимать / арендовать", "verb", ["Ich möchte ein Auto mieten."], "Rent.", ["покупать", "продавать", "строить"]),
    createWord(396, "die Miete", "арендная плата", "die", ["Die Miete ist hoch."], "Rent (money).", ["цена", "зарплата", "налог"]),
    createWord(397, "die Milch", "молоко", "die", ["Kaffee mit Milch."], "Milk.", ["вода", "сок", "чай"]),
    createWord(398, "mit", "с", "prep", ["Ich gehe mit meinem Freund."], "With.", ["без", "для", "от"]),
    createWord(399, "mitbringen", "приносить с собой", "verb", ["Soll ich was mitbringen?"], "Bring along.", ["оставлять", "забывать", "терять"]),
    createWord(400, "mitkommen", "идти вместе", "verb", ["Kommst du mit?"], "Come along.", ["уходить", "оставаться", "ждать"]),
    createWord(401, "mitmachen", "участвовать", "verb", ["Warum macht ihr nicht mit?"], "Join in.", ["смотреть", "уходить", "спать"]),
    createWord(402, "mitnehmen", "брать с собой", "verb", ["Nehmen wir den Hund mit?"], "Take along.", ["оставлять", "бросать", "давать"]),
    createWord(403, "die Mitte", "середина", "die", ["In der Mitte."], "Middle.", ["начало", "конец", "край"]),
    createWord(404, "die Möbel", "мебель", "pl", ["Sind die Möbel neu?"], "Furniture.", ["одежда", "посуда", "техника"]),
    createWord(405, "möchten", "хотеть бы (вежливо)", "verb", ["Was möchten Sie trinken?"], "Would like.", ["ненавидеть", "должен", "мочь"]),
    createWord(406, "mögen", "любить / нравиться", "verb", ["Magst du Kaffee?"], "Like.", ["hassen", "trinken", "essen"]),
    createWord(407, "möglich", "возможный", "adj", ["Ist das möglich?"], "Possible.", ["невозможно", "сложно", "просто"]),
    createWord(408, "der Moment", "момент", "der", ["Einen Moment bitte."], "Moment.", ["час", "год", "вечность"]),
    createWord(409, "morgen", "завтра", "adv", ["Morgen beginnt die Schule."], "Tomorrow.", ["сегодня", "вчера", "сейчас"]),
    createWord(410, "müde", "усталый", "adj", ["Ich bin müde."], "Tired.", ["бодрый", "веселый", "активный"]),
    createWord(411, "der Mund", "рот", "der", ["Öffnen Sie den Mund."], "Mouth.", ["нос", "глаз", "ухо"]),
    createWord(412, "müssen", "быть должным", "verb", ["Ich muss arbeiten."], "Must/Have to.", ["хотеть", "мочь", "любить"]),
    createWord(413, "die Mutter", "мать", "die", ["Meine Mutter heißt Eva."], "Mother.", ["отец", "брат", "сестра"]),

    // --- PART 4: N - R ---
// Paste inside initialData array

    // --- N ---
    createWord(414, "nach", "в / после", "prep", ["Ich fliege nach München.", "Es ist 5 nach 12."], "To (cities/countries) OR After (time).", ["из", "до", "перед"]),
    createWord(415, "nächster", "следующий", "adj", ["Sehen wir uns nächste Woche?"], "Next.", ["предыдущий", "прошлый", "этот"]),
    createWord(416, "der Name", "имя / фамилия", "der", ["Mein Name ist Thomas Schmidt."], "Name.", ["адрес", "город", "возраст"]),
    createWord(417, "nehmen", "брать", "verb", ["Ich nehme das Hähnchen."], "Take.", ["давать", "класть", "оставлять"]),
    createWord(418, "nein", "нет", "part", ["Nein, ich habe keine Zeit."], "No.", ["да", "может быть", "конечно"]),
    createWord(419, "neu", "новый", "adj", ["Ich bin der neue Kollege."], "New.", ["старый", "плохой", "сломанный"]),
    createWord(420, "nicht", "не", "part", ["Das stimmt nicht."], "Not.", ["да", "очень", "много"]),
    createWord(421, "nichts", "ничего", "pron", ["Das macht nichts.", "Hier kaufe ich nichts."], "Nothing.", ["все", "что-то", "много"]),
    createWord(422, "nie", "никогда", "adv", ["Er kommt nie pünktlich."], "Never.", ["всегда", "часто", "иногда"]),
    createWord(423, "noch", "еще", "adv", ["Ich habe noch 20 Euro."], "Still/Yet.", ["уже", "больше", "никогда"]),
    createWord(424, "normal", "нормальный", "adj", ["Sein Gewicht ist normal."], "Normal.", ["странный", "плохой", "новый"]),
    createWord(425, "die Nummer", "номер", "die", ["Sie haben Zimmer Nummer 12."], "Number.", ["буква", "слово", "текст"]),
    createWord(426, "nur", "только", "adv", ["Ich möchte nur Wasser."], "Only.", ["все", "много", "также"]),

    // --- O ---
    createWord(427, "oben", "наверху", "adv", ["Ich wohne oben."], "Above/Upstairs.", ["внизу", "справа", "слева"]),
    createWord(428, "das Obst", "фрукты", "das", ["Ich esse gern Obst."], "Fruit.", ["овощи", "мясо", "хлеб"]),
    createWord(429, "oder", "или", "konj", ["Kaffee oder Tee?"], "Or.", ["и", "но", "потому что"]),
    createWord(430, "öffnen", "открывать", "verb", ["Ich öffne die Tür."], "Open.", ["закрывать", "ломать", "красить"]),
    createWord(431, "geöffnet", "открыт", "adj", ["Der Laden ist geöffnet."], "Opened.", ["закрыт", "занят", "свободен"]),
    createWord(432, "oft", "часто", "adv", ["Petra treffe ich oft."], "Often.", ["редко", "никогда", "однажды"]),
    createWord(433, "ohne", "без", "prep", ["Ohne Geld kann er nichts kaufen."], "Without.", ["с", "для", "около"]),
    createWord(434, "das Öl", "растительное масло", "das", ["Salat ohne Öl."], "Oil.", ["вода", "уксус", "соль"]),
    createWord(435, "die Oma", "бабушка", "die", ["Meine Oma ist schon tot."], "Grandma.", ["дедушка", "мама", "папа"]),
    createWord(436, "der Opa", "дедушка", "der", ["Mein Opa heißt Hans."], "Grandpa.", ["бабушка", "папа", "дядя"]),
    createWord(437, "die Ordnung", "порядок", "die", ["Das ist in Ordnung."], "Order/Okay.", ["хаос", "мусор", "проблема"]),
    createWord(438, "der Ort", "место / населенный пункт", "der", ["Der Ort liegt am Meer."], "Place/Town.", ["город", "страна", "мир"]),

    // --- P ---
    createWord(439, "das Papier", "бумага", "das", ["Hier sind Papier und Bleistift."], "Paper.", ["ручка", "стол", "стул"]),
    createWord(440, "die Papiere", "документы", "pl", ["Haben Sie Ihre Papiere?"], "Documents/Papers.", ["деньги", "ключи", "вещи"]),
    createWord(441, "der Partner", "партнер", "der", ["Sie ist meine Partnerin."], "Partner.", ["враг", "сосед", "чужой"]),
    createWord(442, "die Party", "вечеринка", "die", ["Wir machen eine Party."], "Party.", ["работа", "урок", "сон"]),
    createWord(443, "der Pass", "паспорт", "der", ["Im Hotel brauchst du den Pass."], "Passport.", ["билет", "виза", "права"]),
    createWord(444, "die Pause", "пауза / перерыв", "die", ["Wir machen eine Pause."], "Break.", ["работа", "урок", "начало"]),
    createWord(445, "der Plan", "план / карта", "der", ["Ich kaufe einen Stadtplan."], "Plan/Map.", ["книга", "письмо", "билет"]),
    createWord(446, "der Platz", "место / площадь", "der", ["Nehmen Sie Platz!"], "Place/Seat/Square.", ["улица", "дом", "парк"]),
    createWord(447, "die Polizei", "полиция", "die", ["Holen Sie die Polizei!"], "Police.", ["врач", "пожарные", "учитель"]),
    createWord(448, "die Pommes frites", "картофель фри", "pl", ["Hähnchen mit Pommes."], "French fries.", ["суп", "салат", "рис"]),
    createWord(449, "die Post", "почта", "die", ["Wo ist die Post?"], "Post office.", ["банк", "школа", "магазин"]),
    createWord(450, "die Postleitzahl", "почтовый индекс", "die", ["Wie ist Ihre Postleitzahl?"], "Zip code.", ["номер дома", "телефон", "дата"]),
    createWord(451, "das Praktikum", "практика (стажировка)", "das", ["Ich mache ein Praktikum."], "Internship.", ["работа", "учеба", "отпуск"]),
    createWord(452, "die Praxis", "врачебная практика / кабинет", "die", ["Die Praxis ist geöffnet."], "Doctor's office.", ["больница", "аптека", "дом"]),
    createWord(453, "der Preis", "цена", "der", ["Die Preise sind hoch."], "Price.", ["скидка", "счет", "деньги"]),
    createWord(454, "das Problem", "проблема", "das", ["Mein Problem ist die Sprache."], "Problem.", ["решение", "ответ", "вопрос"]),
    createWord(455, "der Prospekt", "проспект / брошюра", "der", ["Schicken Sie mir einen Prospekt."], "Brochure.", ["книга", "газета", "письмо"]),
    createWord(456, "die Prüfung", "экзамен", "die", ["Die Prüfung ist schwer."], "Exam.", ["урок", "тест", "игра"]),
    createWord(457, "pünktlich", "пунктуальный / вовремя", "adj", ["Der Bus ist pünktlich."], "On time.", ["поздно", "рано", "долго"]),

    // --- R ---
    createWord(458, "Rad fahren", "кататься на велосипеде", "verb", ["Das Kind kann schon Rad fahren."], "Ride a bike.", ["бегать", "плавать", "летать"]),
    createWord(459, "rauchen", "курить", "verb", ["Ich rauche nicht."], "Smoke.", ["пить", "есть", "спать"]),
    createWord(460, "der Raum", "помещение / комната", "der", ["Der Unterricht ist in Raum 332."], "Room.", ["дом", "улица", "парк"]),
    createWord(461, "die Rechnung", "счет", "die", ["Die Rechnung bitte!"], "Bill/Check.", ["меню", "заказ", "деньги"]),
    createWord(462, "rechts", "справа / направо", "adv", ["Hier rechts."], "Right.", ["слева", "прямо", "назад"]),
    createWord(463, "regnen", "идти (о дожде)", "verb", ["Heute regnet es."], "To rain.", ["светить", "снег", "ветер"]),
    createWord(464, "der Regen", "дождь", "der", ["Bei diesem Regen gehe ich nicht raus."], "Rain.", ["солнце", "снег", "туман"]),
    createWord(465, "der Reis", "рис", "der", ["Ich esse gern Reis."], "Rice.", ["картофель", "макароны", "хлеб"]),
    createWord(466, "reisen", "путешествовать", "verb", ["Ich reise gern."], "Travel.", ["сидеть", "работать", "спать"]),
    createWord(467, "die Reise", "путешествие", "die", ["Wir machen eine Reise."], "Trip.", ["работа", "учеба", "сон"]),
    createWord(468, "das Reisebüro", "турбюро", "das", ["Mein Mann arbeitet im Reisebüro."], "Travel agency.", ["отель", "вокзал", "банк"]),
    createWord(469, "der Reiseführer", "путеводитель / гид", "der", ["Ich kaufe einen Reiseführer."], "Guidebook/Guide.", ["книга", "карта", "билет"]),
    createWord(470, "reparieren", "ремонтировать", "verb", ["Er hat das Fahrrad repariert."], "Repair.", ["ломать", "покупать", "продавать"]),
    createWord(471, "die Reparatur", "ремонт", "die", ["Die Reparatur ist teuer."], "Repair.", ["покупка", "продажа", "обмен"]),
    createWord(472, "das Restaurant", "ресторан", "das", ["Wir essen im Restaurant."], "Restaurant.", ["кафе", "бар", "дом"]),
    createWord(473, "die Rezeption", "ресепшн", "die", ["Fragen Sie an der Rezeption."], "Reception.", ["комната", "кухня", "бар"]),
    createWord(474, "richtig", "правильный", "adj", ["Das ist richtig."], "Correct.", ["неправильно", "ложно", "плохо"]),
    createWord(475, "riechen", "пахнуть / нюхать", "verb", ["Der Wein riecht gut."], "Smell.", ["смотреть", "слышать", "пробовать"]),
    createWord(476, "ruhig", "спокойный / тихий", "adj", ["Ich möchte ein ruhiges Zimmer."], "Quiet.", ["шумный", "громкий", "активный"]),

    // --- PART 5: S - Z ---
// Paste inside initialData array

    // --- S ---
    createWord(477, "der Saft", "сок", "der", ["Möchtest du einen Saft?"], "Juice.", ["вода", "чай", "суп"]),
    createWord(478, "sagen", "говорить / сказать", "verb", ["Sag mal, wie geht es dir?"], "Say.", ["молчать", "слушать", "читать"]),
    createWord(479, "der Salat", "салат", "der", ["Der Salat schmeckt gut."], "Salad.", ["мясо", "хлеб", "рыба"]),
    createWord(480, "das Salz", "соль", "das", ["Kann ich bitte Salz haben?"], "Salt.", ["сахар", "перец", "масло"]),
    createWord(481, "der Satz", "предложение (фраза)", "der", ["Der Satz ist einfach."], "Sentence.", ["слово", "буква", "текст"]),
    createWord(482, "die S-Bahn", "городская электричка", "die", ["Ich nehme die S-Bahn."], "Suburban train.", ["метро", "автобус", "такси"]),
    createWord(483, "der Schalter", "окошко (касса) / выключатель", "der", ["Gehen Sie zum Schalter 3."], "Counter.", ["дверь", "стол", "стул"]),
    createWord(484, "scheinen", "светить", "verb", ["Die Sonne scheint."], "Shine.", ["идти (дождь)", "темнеть", "дуть"]),
    createWord(485, "schicken", "посылать / отправлять", "verb", ["Bitte schicken Sie mir eine E-Mail."], "Send.", ["получать", "брать", "читать"]),
    createWord(486, "das Schild", "табличка / знак", "das", ["Haben Sie das Schild nicht gesehen?"], "Sign.", ["дорога", "стена", "окно"]),
    createWord(487, "der Schinken", "ветчина", "der", ["Ein Schinkenbrot, bitte."], "Ham.", ["сыр", "масло", "хлеб"]),
    createWord(488, "schlafen", "спать", "verb", ["Ich schlafe gut."], "Sleep.", ["вставать", "бегать", "работать"]),
    createWord(489, "schlecht", "плохой", "adj", ["Mir ist schlecht.", "Das Wetter ist schlecht."], "Bad.", ["хороший", "добрый", "красивый"]),
    createWord(490, "schließen", "закрывать", "verb", ["Bitte schließen Sie die Tür."], "Close.", ["открывать", "ломать", "красить"]),
    createWord(491, "der Schluss", "конец", "der", ["Zum Schluss geben wir uns die Hand."], "End/Conclusion.", ["начало", "середина", "старт"]),
    createWord(492, "der Schlüssel", "ключ", "der", ["Hier ist der Schlüssel."], "Key.", ["замок", "дверь", "дом"]),
    createWord(493, "schmecken", "быть на вкус / нравиться (о еде)", "verb", ["Schmeckt das gut?"], "Taste.", ["смотреть", "слышать", "нюхать"]),
    createWord(494, "schnell", "быстрый", "adj", ["Er fährt schnell."], "Fast.", ["медленный", "тихий", "спокойный"]),
    createWord(495, "schon", "уже", "adv", ["Ist das Essen schon fertig?"], "Already.", ["еще", "потом", "никогда"]),
    createWord(496, "schön", "красивый / прекрасный", "adj", ["Schönen Urlaub!", "Das ist schön."], "Beautiful.", ["уродливый", "плохой", "старый"]),
    createWord(497, "der Schrank", "шкаф", "der", ["Die Gläser stehen im Schrank."], "Cupboard/Closet.", ["стол", "кровать", "стул"]),
    createWord(498, "schreiben", "писать", "verb", ["Er schreibt eine E-Mail."], "Write.", ["читать", "слушать", "говорить"]),
    createWord(499, "der Schuh", "ботинок / обувь", "der", ["Zieh die Schuhe aus."], "Shoe.", ["носок", "брюки", "шапка"]),
    createWord(500, "die Schule", "школа", "die", ["Meine Tochter geht in die Schule."], "School.", ["университет", "работа", "детсад"]),
    createWord(501, "schwer", "тяжелый / трудный", "adj", ["Ist das Gepäck schwer?", "Das ist eine schwere Aufgabe."], "Heavy/Hard.", ["легкий", "простой", "мягкий"]),
    createWord(502, "die Schwester", "сестра", "die", ["Meine Schwester kommt heute."], "Sister.", ["брат", "мать", "отец"]),
    createWord(503, "schwimmen", "плавать", "verb", ["Ich schwimme gern."], "Swim.", ["бегать", "летать", "ходить"]),
    createWord(504, "der See", "озеро", "der", ["Wir fahren zum See."], "Lake.", ["море", "река", "бассейн"]),
    createWord(505, "sehen", "видеть / смотреть", "verb", ["Ich kann dich nicht sehen."], "See.", ["слышать", "говорить", "трогать"]),
    createWord(506, "sehr", "очень", "adv", ["Danke sehr!"], "Very.", ["мало", "немного", "почти"]),
    createWord(507, "sein", "быть", "verb", ["Ich bin müde."], "To be.", ["иметь", "делать", "стать"]),
    createWord(508, "seit", "с (какого-то времени)", "prep", ["Ich wohne hier seit 3 Jahren."], "Since/For.", ["до", "после", "в"]),
    createWord(509, "selbstständig", "самостоятельный / частный предприниматель", "adj", ["Er ist selbstständig."], "Self-employed/Independent.", ["зависимый", "наемный", "ленивый"]),
    createWord(510, "sich", "себя / себе", "pron", ["Sie müssen sich anmelden."], "Oneself (Reflexive).", ["меня", "тебя", "его"]),
    createWord(511, "sie", "она / они", "pron", ["Wie heißt sie?"], "She/They.", ["он", "мы", "я"]),
    createWord(512, "Sie", "Вы (вежливая форма)", "pron", ["Wie heißen Sie?"], "You (formal).", ["ты", "он", "мы"]),
    createWord(513, "sitzen", "сидеть", "verb", ["Wo sitzen Sie?"], "Sit.", ["стоять", "лежать", "идти"]),
    createWord(514, "so", "так", "adv", ["Sie müssen das so machen."], "So/Thus.", ["иначе", "плохо", "хорошо"]),
    createWord(515, "das Sofa", "диван", "das", ["Das Sofa ist neu."], "Sofa.", ["стул", "кровать", "стол"]),
    createWord(516, "sofort", "сразу / немедленно", "adv", ["Bitte antworten Sie sofort."], "Immediately.", ["потом", "завтра", "никогда"]),
    createWord(517, "der Sohn", "сын", "der", ["Das ist mein Sohn."], "Son.", ["дочь", "отец", "брат"]),
    createWord(518, "sollen", "быть должным (совет/приказ)", "verb", ["Soll ich kommen?"], "Should.", ["мочь", "хотеть", "знать"]),
    createWord(519, "die Sonne", "солнце", "die", ["Die Sonne scheint."], "Sun.", ["луна", "звезда", "облако"]),
    createWord(520, "spät", "поздно", "adj", ["Es ist schon spät."], "Late.", ["рано", "вовремя", "долго"]),
    createWord(521, "die Speisekarte", "меню", "die", ["Bringen Sie mir die Speisekarte."], "Menu.", ["счет", "тарелка", "вилка"]),
    createWord(522, "spielen", "играть", "verb", ["Die Kinder spielen."], "Play.", ["работать", "учить", "спать"]),
    createWord(523, "der Sport", "спорт", "der", ["Ich mache viel Sport."], "Sport.", ["музыка", "кино", "сон"]),
    createWord(524, "die Sprache", "язык", "die", ["Welche Sprache sprichst du?"], "Language.", ["слово", "буква", "книга"]),
    createWord(525, "sprechen", "говорить", "verb", ["Kann ich mit Herrn Klein sprechen?"], "Speak.", ["молчать", "слушать", "петь"]),
    createWord(526, "die Stadt", "город", "die", ["Heidelberg ist eine alte Stadt."], "City.", ["деревня", "страна", "улица"]),
    createWord(527, "stehen", "стоять", "verb", ["Der Bus steht an der Haltestelle."], "Stand.", ["сидеть", "лежать", "идти"]),
    createWord(528, "die Stelle", "место / должность", "die", ["Ich habe eine neue Stelle."], "Job/Place.", ["дом", "школа", "парк"]),
    createWord(529, "stellen", "ставить", "verb", ["Stell die Tasche hierhin."], "Put/Place.", ["класть", "вешать", "бросать"]),
    createWord(530, "der Stock", "этаж", "der", ["Im ersten Stock."], "Floor/Story.", ["подвал", "крыша", "лифт"]),
    createWord(531, "die Straße", "улица", "die", ["In welcher Straße wohnen Sie?"], "Street.", ["город", "дом", "комната"]),
    createWord(532, "die Straßenbahn", "трамвай", "die", ["Wo fährt die Straßenbahn?"], "Tram.", ["автобус", "метро", "такси"]),
    createWord(533, "studieren", "учиться (в вузе)", "verb", ["Ich studiere in Mainz."], "Study (university).", ["работать", "учить", "играть"]),
    createWord(534, "die Stunde", "час (длительность)", "die", ["Ich bin in einer Stunde zurück."], "Hour.", ["минута", "секунда", "день"]),
    createWord(535, "suchen", "искать", "verb", ["Suchst du etwas?"], "Search.", ["находить", "терять", "прятать"]),

    // --- T ---
    createWord(536, "tanzen", "танцевать", "verb", ["Tanzen Sie gern?"], "Dance.", ["петь", "стоять", "сидеть"]),
    createWord(537, "die Tasche", "сумка / карман", "die", ["Ich habe die Schlüssel in der Tasche."], "Bag/Pocket.", ["чемодан", "пакет", "коробка"]),
    createWord(538, "das Taxi", "такси", "das", ["Er fährt mit dem Taxi."], "Taxi.", ["bus", "bahn", "auto"]),
    createWord(539, "der Tee", "чай", "der", ["Ich trinke Tee."], "Tea.", ["kaffee", "wasser", "saft"]),
    createWord(540, "telefonieren", "говорить по телефону", "verb", ["Darf ich telefonieren?"], "Phone.", ["schreiben", "sprechen", "lesen"]),
    createWord(541, "der Termin", "встреча / прием", "der", ["Ich habe einen Termin."], "Appointment.", ["zeit", "datum", "jahr"]),
    createWord(542, "teuer", "дорогой", "adj", ["Das ist zu teuer."], "Expensive.", ["billig", "günstig", "kostenlos"]),
    createWord(543, "der Tisch", "стол", "der", ["Das Essen steht auf dem Tisch."], "Table.", ["stuhl", "bett", "schrank"]),
    createWord(544, "die Tochter", "дочь", "die", ["Das ist meine Tochter."], "Daughter.", ["sohn", "mutter", "vater"]),
    createWord(545, "die Toilette", "туалет", "die", ["Wo ist die Toilette?"], "Toilet.", ["bad", "kueche", "zimmer"]),
    createWord(546, "treffen", "встречать", "verb", ["Wir treffen uns um 8."], "Meet.", ["sehen", "gehen", "kommen"]),
    createWord(547, "die Treppe", "лестница", "die", ["Die Treppe hoch."], "Stairs.", ["aufzug", "tür", "fenster"]),
    createWord(548, "trinken", "пить", "verb", ["Möchtest du etwas trinken?"], "Drink.", ["essen", "kochen", "schlafen"]),
    createWord(549, "tschüss", "пока", "int", ["Tschüss, bis morgen!"], "Bye.", ["hallo", "guten tag", "auf wiedersehen"]),

    // --- U ---
    createWord(550, "über", "над / о", "prep", ["Über uns wohnt Familie Meier."], "Over/About.", ["unter", "neben", "in"]),
    createWord(551, "übernachten", "ночевать", "verb", ["Du kannst bei mir übernachten."], "Stay overnight.", ["wohnen", "schlafen", "bleiben"]),
    createWord(552, "überweisen", "переводить (деньги)", "verb", ["Sie können das Geld überweisen."], "Transfer.", ["bezahlen", "kaufen", "sparen"]),
    createWord(553, "die Uhr", "часы / час (время)", "die", ["Es ist vier Uhr."], "Clock/O'clock.", ["zeit", "stunde", "minute"]),
    createWord(554, "um", "в (о времени) / вокруг", "prep", ["Er kommt um sieben."], "At/Around.", ["am", "im", "gegen"]),
    createWord(555, "umziehen", "переезжать", "verb", ["Wir ziehen bald um."], "Move (house).", ["bleiben", "wohnen", "bauen"]),
    createWord(556, "und", "и", "konj", ["Peter und Hans."], "And.", ["oder", "aber", "denn"]),
    createWord(557, "unten", "внизу", "adv", ["Er wohnt unten."], "Downstairs.", ["oben", "rechts", "links"]),
    createWord(558, "unter", "под", "prep", ["Unter dem Tisch."], "Under.", ["über", "auf", "neben"]),
    createWord(559, "der Unterricht", "занятие / урок", "der", ["Der Unterricht beginnt."], "Class/Lesson.", ["pause", "schule", "arbeit"]),
    createWord(560, "unterschreiben", "подписывать", "verb", ["Wo muss ich unterschreiben?"], "Sign.", ["schreiben", "lesen", "malen"]),
    createWord(561, "der Urlaub", "отпуск", "der", ["Ich habe Urlaub."], "Vacation.", ["arbeit", "schule", "stress"]),

    // --- V ---
    createWord(562, "der Vater", "отец", "der", ["Mein Vater ist Arzt."], "Father.", ["mutter", "bruder", "sohn"]),
    createWord(563, "verboten", "запрещено", "adj", ["Rauchen verboten."], "Forbidden.", ["erlaubt", "möglich", "frei"]),
    createWord(564, "verdienen", "зарабатывать", "verb", ["Ich verdiene gut."], "Earn.", ["ausgeben", "bezahlen", "kaufen"]),
    createWord(565, "verheiratet", "женатый / замужем", "adj", ["Ich bin verheiratet."], "Married.", ["ledig", "geschieden", "verwitwet"]),
    createWord(566, "verkaufen", "продавать", "verb", ["Er verkauft sein Auto."], "Sell.", ["kaufen", "mieten", "schenken"]),
    createWord(567, "vermieten", "сдавать в аренду", "verb", ["Die Wohnung ist vermietet."], "Rent out.", ["mieten", "kaufen", "wohnen"]),
    createWord(568, "verstehen", "понимать", "verb", ["Ich verstehe das nicht."], "Understand.", ["wissen", "hören", "fragen"]),
    createWord(569, "viel", "много", "adj", ["Ich habe viel Zeit."], "Much/Many.", ["wenig", "kein", "alles"]),
    createWord(570, "vielleicht", "может быть", "adv", ["Vielleicht komme ich."], "Maybe.", ["sicher", "bestimmt", "nie"]),
    createWord(571, "von", "от / из", "prep", ["Das Auto von Felix."], "From/Of.", ["zu", "bei", "mit"]),
    createWord(572, "vor", "перед / до", "prep", ["Vor dem Haus."], "Before/In front of.", ["hinter", "nach", "neben"]),
    createWord(573, "der Vorname", "имя", "der", ["Mein Vorname ist Eva."], "First name.", ["nachname", "name", "adresse"]),
    createWord(574, "Vorsicht", "Осторожно", "int", ["Vorsicht! Auto!"], "Caution.", ["hallo", "danke", "bitte"]),
    createWord(575, "sich vorstellen", "представляться", "verb", ["Können Sie sich vorstellen?"], "Introduce oneself.", ["verstehen", "fragen", "antworten"]),

    // --- W ---
    createWord(576, "wann", "когда", "adv", ["Wann kommst du?"], "When.", ["wo", "wie", "wer"]),
    createWord(577, "warten", "ждать", "verb", ["Ich warte auf den Bus."], "Wait.", ["gehen", "kommen", "laufen"]),
    createWord(578, "warum", "почему", "adv", ["Warum kommst du nicht?"], "Why.", ["weil", "wann", "wo"]),
    createWord(579, "was", "что", "pron", ["Was ist das?"], "What.", ["wer", "wie", "wo"]),
    createWord(580, "waschen", "мыть / стирать", "verb", ["Ich muss waschen."], "Wash.", ["putzen", "kochen", "bügeln"]),
    createWord(581, "das Wasser", "вода", "das", ["Ein Glas Wasser bitte."], "Water.", ["bier", "wein", "saft"]),
    createWord(582, "weh tun", "болеть", "verb", ["Mein Kopf tut weh."], "Hurt.", ["gut tun", "helfen", "heilen"]),
    createWord(583, "der Wein", "вино", "der", ["Ich trinke Wein."], "Wine.", ["bier", "wasser", "saft"]),
    createWord(584, "weit", "далеко", "adj", ["Der Weg ist weit."], "Far.", ["nah", "kurz", "eng"]),
    createWord(585, "weiter", "дальше", "adv", ["Der Bus fährt nicht weiter."], "Further.", ["zurück", "stopp", "hier"]),
    createWord(586, "die Welt", "мир", "die", ["Die Welt ist groß."], "World.", ["land", "stadt", "dorf"]),
    createWord(587, "wenig", "мало", "adj", ["Ich habe wenig Zeit."], "Little/Few.", ["viel", "alles", "genug"]),
    createWord(588, "wer", "кто", "pron", ["Wer ist das?"], "Who.", ["was", "wo", "wie"]),
    createWord(589, "werden", "становиться", "verb", ["Er will Arzt werden."], "Become.", ["sein", "haben", "bleiben"]),
    createWord(590, "das Wetter", "погода", "das", ["Das Wetter ist schön."], "Weather.", ["sonne", "regen", "wind"]),
    createWord(591, "wichtig", "важный", "adj", ["Das ist wichtig."], "Important.", ["unwichtig", "egal", "klein"]),
    createWord(592, "wie", "как", "adv", ["Wie heißt du?"], "How.", ["was", "wer", "wo"]),
    createWord(593, "wiederholen", "повторять", "verb", ["Bitte wiederholen Sie."], "Repeat.", ["verstehen", "sagen", "hören"]),
    createWord(594, "das Wiedersehen", "свидание (прощание)", "das", ["Auf Wiedersehen!"], "Reunion/Goodbye.", ["hallo", "tschüss", "guten tag"]),
    createWord(595, "wie viel", "сколько", "adv", ["Wie viel kostet das?"], "How much.", ["wann", "wo", "was"]),
    createWord(596, "willkommen", "добро пожаловать", "adj", ["Herzlich willkommen!"], "Welcome.", ["tschüss", "weg", "raus"]),
    createWord(597, "wir", "мы", "pron", ["Wir lernen Deutsch."], "We.", ["ich", "ihr", "sie"]),
    createWord(598, "wissen", "знать (факт)", "verb", ["Ich weiß es nicht."], "Know.", ["kennen", "denken", "glauben"]),
    createWord(599, "wo", "где", "adv", ["Wo wohnst du?"], "Where.", ["woher", "wohin", "wann"]),
    createWord(600, "woher", "откуда", "adv", ["Woher kommen Sie?"], "Where from.", ["wohin", "wo", "wann"]),
    createWord(601, "wohin", "куда", "adv", ["Wohin gehst du?"], "Where to.", ["woher", "wo", "wann"]),
    createWord(602, "wohnen", "жить / проживать", "verb", ["Ich wohne in Berlin."], "Live/Reside.", ["leben", "sein", "arbeiten"]),
    createWord(603, "die Wohnung", "квартира", "die", ["Die Wohnung ist groß."], "Apartment.", ["haus", "zimmer", "hotel"]),
    createWord(604, "wollen", "хотеть", "verb", ["Ich will schlafen."], "Want.", ["können", "müssen", "sollen"]),
    createWord(605, "das Wort", "слово", "das", ["Ich verstehe das Wort nicht."], "Word.", ["satz", "text", "buch"]),

    // --- Z ---
    createWord(606, "zahlen", "платить", "verb", ["Zahlen bitte!"], "Pay.", ["kaufen", "bestellen", "essen"]),
    createWord(607, "die Zeit", "время", "die", ["Ich habe keine Zeit."], "Time.", ["uhr", "stunde", "tag"]),
    createWord(608, "die Zeitung", "газета", "die", ["Ich lese die Zeitung."], "Newspaper.", ["buch", "heft", "brief"]),
    createWord(609, "die Zigarette", "сигарета", "die", ["Er raucht Zigaretten."], "Cigarette.", ["feuer", "rauch", "asche"]),
    createWord(610, "das Zimmer", "комната / номер", "das", ["Das Zimmer ist klein."], "Room.", ["haus", "wohnung", "kueche"]),
    createWord(611, "der Zoll", "таможня", "der", ["Wir müssen durch den Zoll."], "Customs.", ["polizei", "pass", "grenze"]),
    createWord(612, "zu", "к / закрыто / слишком", "prep", ["Zum Bahnhof. / Die Tür ist zu."], "To/Closed/Too.", ["auf", "offen", "weg"]),
    createWord(613, "zufrieden", "довольный", "adj", ["Ich bin zufrieden."], "Satisfied.", ["traurig", "böse", "müde"]),
    createWord(614, "der Zug", "поезд", "der", ["Der Zug kommt gleich."], "Train.", ["bus", "auto", "flugzeug"]),
    createWord(615, "zurück", "назад / обратно", "adv", ["Einmal Frankfurt und zurück."], "Back.", ["vor", "hin", "weg"]),
    createWord(616, "zusammen", "вместе", "adv", ["Wir essen zusammen."], "Together.", ["allein", "getrennt", "einsam"]),
    createWord(617, "zwischen", "между", "prep", ["Zwischen 8 und 10 Uhr."], "Between.", ["neben", "unter", "über"])
];